library(latex2exp)
options(scipen=999)
birds = read.csv("birds.csv")
id = sample(1:nrow(birds),1)
gen = "fuck" #as.character(birds[id,1])
species = "it" #as.character(birds[id,2])
mu = as.numeric(birds[id,3])
sigma = as.numeric(birds[id,4])

dfs = c(12:35)
df = sample(dfs,1)
n = df+1
cls = c(0.8,0.9,0.95,0.96,0.98,0.99,0.995)
cl = sample(cls,1)
tstar = round(qt((cl+1)/2,df),2)
sam = rnorm(n,mu,sigma)
xbar = round(mean(sam),2)
s = signif(sd(sam),3)
se = signif(s/sqrt(n),3)
lb = signif(xbar-tstar*se,3)
ub = signif(xbar+tstar*se,3)

print(id)
print(gen)
print(species)
print(mu)
print(sigma)
print(xbar)
